name: The Mall in St. James’s Park
author: Nicolas “Niols” Jeannerod
kind: 32-bar strathspey for three couples in a three-couple longwise set
short-kind: S32 3/3L
tunes:
  - the-mall-in-st-james-s-park
