#!/usr/bin/env python3

import sys
import time

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options as FirefoxOptions
from selenium.webdriver.support.wait import WebDriverWait

source = sys.argv[1]
target = sys.argv[2]
width  = sys.argv[3]
height = sys.argv[4]

## Get a driver for a headless Firefox.
options = FirefoxOptions()
options.headless = True
driver = webdriver.Firefox(options=options)

## Get the requested page and give it time to load.
driver.get(source)
time.sleep(1)

## Maximize the window and set its size.
driver.maximize_window()
driver.set_window_size(width, height)

## Save a screenshot and leave.
driver.save_screenshot(target)
driver.quit()
