name: The Reel of the 51st Confusion
author: Anne Lanvin, Corentin Lefèvre, Isabelle Herlant, Louise Baltera, Nicolas “Niols” Jeannerod & Victor Lanvin
short-author: Anne Lanvin et al.
kind: 32-bar reel for three couples in a three-couple longwise set
short-kind: R32 3/3L
tunes:
  - name: The Drunken Piper
    author: Alexander McLeod
  - the-sober-piper
