#+title: Database

* Dance

** Dance Description

A dance description is a YAML array of items. Items are objects that always
carry a =type= field. They can be either of the following.

*** Text

- type :: =text=
- content :: a string to be included as-is in the output, modulo some escaping
  for HTML entities or TeX special characters.

#+begin_src yaml
type: text
content: |
  1st couple set and cast off one place as 4th couple set and cast up one
  place. 2nd couple step up and 3rd couple step down on bars 3-4.
#+end_src

*** Phrase

- type :: =phrase=
- starts :: an integer representing the starting bar of the phrase.
- ends :: an integer representing the ending bar of the phrase.
- contents :: (mind the /s/) an array of dance description items.

#+begin_src yaml
type: phrase
starts: 1
ends: 4
contents:
  - type: text
    content: |
      1st couple set and cast off one place as 4th couple set and cast up one
      place. 2nd couple step up and 3rd couple step down on bars 3-4.
#+end_src

*** Repeat

- type :: =repeat=
- kind :: the kind of repeat; either =from new positions=, =having passed a couple=,
  or =custom=. In the latter case, see the =text= field.
- text :: (only if =kind= = =custom=) the text for the repeat.

#+begin_src yaml
type: repeat
kind: from new positions
#+end_src

#+begin_src yaml
type: repeat
kind: custom
text: Repeat twenty times without breathing.
#+end_src

*** Devised By

- type :: =devised by=
- deviser :: a string representing the dance deviser.
- more :: (optional) a string to be added after the name of the deviser.

As an example for the =more= field,
#+begin_src yaml
type: devised by
deviser: Nicolas “Niols” Jeannerod
more: in April 2019.
#+end_src
will produce:
#+begin_quote
Devised by Nicolas “Niols” Jeannerod in April 2019.
#+end_quote
while
#+begin_src yaml
type: devised by
deviser: Nicolas “Niols” Jeannerod
#+end_src
will produce:
#+begin_quote
Devised by Nicolas “Niols” Jeannerod.
#+end_quote

*** Music By

- type :: =music by=
- composer :: a string representing the dance composer.
- tune :: (optional) a string representing the name of the tune.
- more :: (optional) a string to be added after the name of the composer or the
  name of the tune. It should start with a capital letter.

#+begin_src yaml
type: music by
composer: Pascaline Latour
more: We cannot thank her enough for this nice tune!
#+end_src
or
#+begin_src yaml
type: music by
composer: Pascaline Latour
tune: La Ville Lumière
#+end_src

* Tune

* Book
