name: Two Blue Clouds in the Grey Sky
author: Claire Cunin & Nicolas “Niols” Jeannerod
kind: 40-bar reel for five couples in a five-couple longwise set
short-kind: R40 5/5L
scddb-id: 19197
book:
  - gone-dancing-2
