---
name: Build and test

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  ############################################################################
  ## Setup Dependencies

  setup-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/composites/setup-nix
        with:
          githubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build environment
        run: nix develop --accept-flake-config --command true

  ############################################################################
  ## Build Website

  build-website:
    runs-on: ubuntu-latest
    needs: setup-dependencies

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/composites/setup-nix
        with:
          githubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build Website
        run: nix develop --accept-flake-config --command make website

      - name: Upload Website as Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: website
          path: _build/website

  ############################################################################
  ## Build Documentation

  build-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install JSON Schema Documentation Generator
        run: |
          pip install json-schema-for-humans==0.41.3

      - name: Generate Documentation for Schemas
        run: |
          mkdir -p _build/doc/schema
          generate-schema-doc 'database/_schema/*.yaml' _build/doc/schema

      - name: Upload Documentation as Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: documentation
          path: _build/doc

  ############################################################################
  ## Test Schemas

  test-schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install YAML to JSON Converter and JSON Schema Validator
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.25.3/yq_linux_386 -qO yq
          chmod +x yq
          pip install jsonschema==4.7.2

      - name: Convert All Schemas and Database to JSON
        run: |
          find database -name '*.yaml' | while read file; do
            printf 'Converting `%s`.\n' "$file"
            ./yq --output-format json "$file" > "${file%.yaml}".json
          done

      - name: Run JSON Validator for all Schemas on the Database
        run: |
          for type in dance tune book; do
            for file in database/$type/*.json; do
              jsonschema --output pretty --instance "$file" database/_schema/$type.json
            done
          done

  ############################################################################
  ## Test Website

  test-website:
    runs-on: ubuntu-latest
    needs: setup-dependencies

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/composites/setup-nix
        with:
          githubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build Test Website
        run: nix develop --accept-flake-config --command make test-website

      - name: Run Tests
        run: nix develop --accept-flake-config --command make tests

      - name: Upload Tests as Artifact
        if: ${{ always() }}
        ## NOTE: The tests are productive even when they fail. Therefore, it
        ## can be useful to upload the archive no matter what. In worst case,
        ## it will be empty.
        uses: actions/upload-artifact@v4.4.0
        with:
          name: tests
          path: _build/tests

  ############################################################################
  ## Run Flake Checks

  test-flake-checks:
    runs-on: ubuntu-latest
    needs: setup-dependencies

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/composites/setup-nix
        with:
          githubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run Flake Checks
        run: nix flake check --print-build-logs --accept-flake-config
