name: Build and Publish

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Build Docker Builder Image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          load: true
          tags: builder
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Website
        run: |
          make website@docker DOCKER_BUILDER_TAG=builder

      - name: Publish Dev Website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          ## Publish `./build` with following commit message...
          publish_dir: ./build
          commit_message: |
            Bump to ${{ github.event.head_commit.id }}: ${{ github.event.head_commit.message }}
          ## to https://github.com/Niols/dev.scd.niols.fr on branch `pages` in
          ## sub-directory $GITHUB_REF while keeping the rest intact...
          external_repository: niols/dev.scd.niols.fr
          publish_branch: pages
          destination_dir: ${{ github.ref }}
          keep_files: true
          ## serving `dev.scd.niols.fr`, with specific PAT.
          cname: dev.scd.niols.fr
          personal_token: ${{ secrets.DEV_PAGES_TOKEN }}

      - name: Publish Main Website to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          ## Publish `./build` with following commit message...
          publish_dir: ./build
          commit_message: |
            Bump to ${{ github.event.head_commit.id }}: ${{ github.event.head_commit.message }}
          ## to branch `pages`, serving `scd.niols.fr`, with standard token.
          publish_branch: pages
          cname: scd.niols.fr
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to the GitHub Package Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Builder Image
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: ghcr.io/niols/scd.niols.fr-builder
          cache-from: type=gha
          cache-to: type=gha,mode=max
