---

name: Check Schemas

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  check-schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Install YAML to JSON Converter and JSON Schema Validator
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.25.3/yq_linux_386 -qO yq
          chmod +x yq
          pip install jsonschema==4.7.2

      - name: Convert All Schemas and Database to JSON
        run: |
          find database -name '*.yaml' | while read file; do
            printf 'Converting `%s`.\n' "$file"
            ./yq --output-format json "$file" > "${file%.yaml}".json
          done

      - name: Run JSON Validator for all Schemas on the Database
        run: |
          for type in dance tune; do
            for file in database/$type/*.json; do
              jsonschema --output pretty --instance "$file" database/_schema/$type.schema.json
            done
          done
