---
name: Publish
run-name: ${{ github.event.workflow_run.display_title }}

on:
  workflow_run:
    workflows: [Build and test]
    types: [completed]

## We specify a concurrency group that spans over all publications, so as to
## avoid different runs clashing together.
concurrency:
  group: publish

jobs:
  ############################################################################
  ## Publish Website

  publish-website:
    name: Publish the website
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.event == 'push'
      && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - name: Download Website from Artifacts
        uses: actions/download-artifact@v4.2.1
        with:
          name: website
          path: ./website
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Publish Website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          ## Publish `./website` with following commit message...
          publish_dir: ./website
          full_commit_message: |
            Bump to ${{ github.event.workflow_run.head_sha }}: ${{ github.event.workflow_run.head_commit.message }}
          ## ...to branch `pages` with the right access token...
          publish_branch: pages
          github_token: ${{ secrets.PAGES_TOKEN }}
          ## ...as the GitHub Actions bot...
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          ## ...serving `scd.niols.fr`.
          cname: scd.niols.fr

  ############################################################################
  ## Publish Dev Website

  publish-dev-website:
    name: Publish the development website
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - run: ls -lah
      - run: cat meta.json

      - name: Consolidate artifacts into a website
        run: |
          mkdir -p ./website
          [ -e ./documentation ] && mv ./documentation ./website/_doc
          [ -e ./tests ] && mv ./tests ./website/_tests

      - name: Prepare metadata for publishing the development website
        run: |
          case ${{ github.event.workflow_run.event }} in
            pull_request)
              pr=${{ github.event.workflow_run.pull_requests[0].number }}
              if [ -z "$pr" ]; then
                echo Could not acquire a PR number.
                exit 2
              fi
              dir=pr/$pr
              ptr="${{ github.repository }}#$pr"
              ;;
            push)
              dir=branch/${{ github.event.workflow_run.head_branch }}
              ptr="${{ github.repository }}@${{ github.event.workflow_run.head_sha }}"
              ;;
            *)
              echo Unexpected event type.
              exit 2
          esac
          msg="Bump \`$dir\` to follow $ptr"
          echo "destination_dir=$dir"
          echo "commit_message=$msg"
          echo "destination_dir=$dir" >> $GITHUB_ENV
          echo "commit_message=$msg" >> $GITHUB_ENV

      - name: Publish development website to GitHub pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          ## Publish `./website` with following commit message...
          publish_dir: ./website
          full_commit_message: ${{ env.commit_message }}
          ## ...to https://github.com/Niols/dev.scd.niols.fr on branch `pages`
          ## with the right access token...
          external_repository: niols/dev.scd.niols.fr
          publish_branch: pages
          personal_token: ${{ secrets.DEV_PAGES_TOKEN }}
          ## ...as the GitHub Actions bot...
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          ## ...in its own sub-directory while keeping the rest intact...
          destination_dir: ${{ env.destination_dir }}
          keep_files: true
          ## ...serving `dev.scd.niols.fr`.
          cname: dev.scd.niols.fr
